//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApi.Database.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementCommentDetail
    {
        public int Id { get; set; }
        public Nullable<int> AnnouncementCommentId { get; set; }
        public string ByUserId { get; set; }
        public string ContentComment { get; set; }
    }
}
